feat: expose new vars
terraform-ibm-modules/terraform-ibm-ocp-all-inclusive pull request #243
Opened 2024-02-02 12:59 UTC by jor2

### Description

Expose new security group variables for `terraform-ibm-base-ocp-vpc`

https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/issues/241

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Expose new security group variables for `terraform-ibm-base-ocp-vpc`

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-02 13:00 UTC, jor2 commented
/run pipeline

2024-02-07 23:19 UTC, jor2 commented
/run pipeline

2024-02-08 00:51 UTC, jor2 commented
/run pipeline

2024-02-08 11:56 UTC, jor2 commented
/run pipeline

2024-02-09 14:20 UTC, ocofaigh requested changes
@jor2 can you resolve conflicts

2024-02-09 14:46 UTC, jor2 commented
/run pipeline

2024-02-09 16:38 UTC, jor2 commented
/run pipeline

2024-02-12 10:36 UTC, jor2 commented
/run pipeline

2024-02-12 10:41 UTC, jor2 commented
/run pipeline

2024-02-13 11:04 UTC, ocofaigh commented on version.tf
> +      version = ">= 1.6.0, < 2.0.0"
I think you meant this right? `">= 1.62.0, < 2.0.0"`

2024-02-13 11:05 UTC, ocofaigh commented on examples/end-to-end-example/version.tf
> +      version = ">= 1.6.0"
did you mean `>= 1.62.0` ?

2024-02-13 11:05 UTC, ocofaigh requested changes
@jor2 I think you have some typos

2024-02-13 13:25 UTC, jor2 commented
/run pipeline

2024-02-13 13:30 UTC, jor2 commented
> @jor2 I think you have some typos

I'm going to have to update all the other modules, is there an easier way?

2024-02-13 14:54 UTC, jor2 commented
/run pipeline

2024-02-13 16:48 UTC, ocofaigh approved these changes

2024-02-13 16:48 UTC, merged

2024-02-13 16:50 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.16.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/releases/tag/v2.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: