feat:Allow to opt out from trusted profile creation
terraform-ibm-modules/terraform-ibm-ocp-all-inclusive pull request #361
Opened 2024-11-25 06:10 UTC by aatreyee2506

### Description

Added a variable to allow the users to opt out of trusted profile creation.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content
Added a variable to allow the users to opt out of trusted profile creation.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-25 06:10 UTC, aatreyee2506 commented
/run pipeline

2024-11-25 07:02 UTC, aatreyee2506 commented
/run pipeline

2024-11-25 07:57 UTC, aatreyee2506 commented
/run pipeline

2024-11-26 06:02 UTC, aatreyee2506 commented
cc : @SarikaSinha

2024-11-26 08:13 UTC, Aashiq-J reviewed
Need to make the same change to the internal module as well.

2024-11-26 08:13 UTC, Aashiq-J commented on main.tf
> -  count                       = (var.logs_agent_enabled && var.logs_agent_iam_mode == "TrustedProfile") ? 1 : 0
Need to add the same logic to line number 110.

2024-11-26 13:04 UTC, aatreyee2506 commented
/run pipeline

2024-12-04 11:35 UTC, ocofaigh requested changes
I'm not sure this is the correct approach. We need to provide the ability for the user to pass an existing trusted profile ID. If the user does not pass one, the module should create one

2024-12-12 09:31 UTC, aatreyee2506 commented
/run pipeline

2024-12-16 09:41 UTC, ocofaigh commented
/run pipeline

2024-12-16 13:16 UTC, ocofaigh approved these changes

2024-12-16 13:17 UTC, merged

2024-12-16 13:18 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 4.3.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/releases/tag/v4.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: